spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mariadb://localhost:3306/tccengsw-noplastic
    username: root
    password: